### ISSUE TITLE
Updating the EDR API Overview (https://ogcapi.ogc.org/edr/overview.html)

### ISSUE THREAD

**Issue by solson-nws** [opengeospatial/ogcapi-environmental-data-retrieval#186]
@chris-little @dblodgett-usgs @boyi-shangguan :  I was tasked with adding some additional language to the overview that spoke to the simple and convenience aspects of EDR.  What follows are some suggestions.  We will likely need to pare this back some.  But, we can discuss those changes at tomorrow's meeting.

The Environmental Data Retrieval (EDR) API can be considered both a **simple API** and a **convenience API**.  It’s considered a **_simple API_** in that:

- From an implementation view, the specification encourages a core plus plug-in model framework
- It doesn’t require much domain knowledge compared to other OGC W*S and API standards
- It makes use of Key/Value pairs
- The metadata is based on the data being queried and is not verbose. 
- The EDR API queries are “fixed” and predefined, meaning you can only query based on what is defined in the OpenAPI definition. 
- The specification encourages the data publisher to publish data in fixed formats that are described within the metadata in a simple way.

It’s considered a **_convenience API_** in that:

- It complements and provides synergy with other OGC API’s.
- The Feature Sampling Geometry type allows users to get exactly the data that they need.
- Users don’t not need to worry about the structure of the underlying data because the EDR-API abstracts that detail from the user.
- It is not constrained to a particular data structure.  The EDR can handle grids, features, etc.
- It hides the complication of the underlying time structure.  Queries are simply an extraction of the data for the time the user selects.
- It’s the responsibility of the publisher to simplify the output, making it very convenient for the user to consume the data.
- Implementations are constrained by the API definition, so all implementations will have the same url structure.

**Comment by KathiSchleidt** [comment]
Stupid simple side thought to the consideration that EDR is a Simple API - would it be in any way possible to rename to "Simple Data Retrieval"?

Background to this thought - if EDR goes out as "Environmental Data Retrieval", this will most likely seriously set back environmental data provision due to the following:
- Most **environmental data** requires provision of measurement metadata for correct interpretation, e.g. air quality, water quality, soil data, biodiversity. To my experience, the two domains who can do without are meteorology and marine, mostly to do with organizational background.
- If OGC propagates an "Environmental Data Retrieval" API, many administrators in environmental agencies will insist on using this, while not understanding how it is not suited to purpose.

To my view, this would be a sad legacy for a well meant standard. Related to thoughts on conneg by profile, that would allow for a solid interlinkage (I do see potential for this API as a simple way of providing data for the other environmental media listed above, as long as it's clear that this is a simple view for rapid portrayal)

**Comment by sgrellet** [comment]
+1 on the idea to rename it 'Simple Data Retrieval API'.
While deeply thinking our vote, we looked at the ESA comment : "Perhaps it could be made clear that this work for any sort of data and not only Environmental...".
Which summarizes well one of our concern as there is nothing Environmental specific in the API spec.

This may look a trivial comment but tooo many people just stop at 'labels' even in our techy line of work

**Comment by chris-little** [comment]
@sgrellet, @KathiSchleidt The EDR API SWG, and the Met Ocean DWG, discussed several times over the last two yearan appropriate name for the API.

"Simple" is too simple and not good enough. For example:
1. "Get me my unique Single Nucelotide Polymerase (SNP) mutations in my y-DNA sample in these BAM and VCF files." 
2. "Which Meccano part numbers are required to build the model Hammerhead Crane."

EDR API does NOT support those types of simple query, as the data do not have any conventional coordinates that can be used in WKT.

Perhaps a better name would be Spatio-Temporal Data Retrieval API, but I am not sure that the STAC people would welcome it. 

I propose that we do not change the name, because:
1. We have been through various OGC process with the EDR name, and issues of expectation and branding may be important;
2. There are no known implementation efforts yet for non-geo spatial-temporal data retrievals (though I am reaching out to a medical community). 
3.  If and when some non-geo examples emerge, a simple facade or proxy should be trivial to build, with whatever name is desired. E.g. '3-D Tomogram Data Retrieval API', which would be much more conveneint for some use cases.

**Comment by KathiSchleidt** [comment]
@chris-little Simple Spatial Data Retrieval - SSDR?

**Comment by hylkevds** [comment]
But it can be used to query features:
1. Give me all traffic lights along my route
2. Give me all houses below my flight path
Plenty of examples that are not Environmental at all.

**Comment by KathiSchleidt** [comment]
Alternatively, riffing off @hylkevds:
1 Give me the state of all traffic lights along my route
2. Give me the current energy consumption of houses below my flight path

**Comment by chris-little** [comment]
@KathiSchleidt `Simple Spatial Data Retrieval - SSDR?` What about temporal? We want to make both z and t first class citizens.

**Comment by chris-little** [comment]
@hylkevds @KathiSchleidt Agreed. As an ordinary person in the street, examples H1, H2 and K1, K2 above are environmental - they are in my environment! Good use cases.

Now please suggest improvements to @solson-nws text above, which is the target of this issue.

**Comment by hylkevds** [comment]
Then you might as well use the name Feature Retrieval API, since everything is a Feature, and by your logic, all features are Environmental.
An ordinary person on the street would NOT call those environmental.

**Comment by KathiSchleidt** [comment]
@chris-little 
for the @solson-nws bit above, how about adding a disclaimer as follows:

- Please be aware that this standard does not support the requirements for professional provision of terrestrial environmental data

I fear the real issue is linguistic, environment has multiple meanings. Here its being used to connotate spatio-temporal, redundant as this is implicit in Open Geospatial. Our fear is that it will be used by Environment Agencies (EPA, EEA) to provide their data without relevant context (not necessary in meteorological data, but at least in accordance with Austrian law, that doesn't fall under the European concept of Environmental data)

**Comment by chris-little** [comment]
@KathiSchleidt I disagree. At least 4 of the implementors,and contributors to EDR API intend to use it for the `professional provision of terrestrial environmental data`. And they will probably use it for safety critical environments too, such as aviation.
I think the API is neutral with respect to legal jurisdictions. If a jurisdiction wishes to impose a restrictive profile on the use of EDR API, such as by mandating the structure and content of response metadata, they are free to do so.
We will discuss this in three hours time at the EDR API SWG.

**Comment by KathiSchleidt** [comment]
@chris-little sorry, my bad, had forgotten that in these modern times, we've replaced birds with air planes. Ah well, guess if its good enough for aviation, sure to suffice for something as trivial as terrestrial environmental data (not really relevant) 
Unfortunately cannot join your SWG as I'll be running a Webinar on OGC API - Features

**Comment by chris-little** [comment]
EDR API SWG 42 unanimously agreed to not change the name, and close this issue.

We propose that we do not change the name, because:

    We have been through various OGC process with the EDR name, and issues of expectation and branding may be important;
    There are no known implementation efforts yet for non-geo spatial-temporal data retrievals (though I am reaching out to a medical community).
    If and when some non-geo examples emerge, a simple facade or proxy should be trivial to build, with whatever name is desired. E.g. '3-D Tomogram Data Retrieval API', which would be much more conveneint for some use cases.
