### ISSUE TITLE
clarify shared parameter requirements

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-environmental-data-retrieval#193]
In the candidate standard, are the following shared parameters required or optional:
- `coords` (doc says optional, YAML/JSON, schemas say required)
- `parameter-name` (docs and YAML/JSON, schemas say required, but wording in Requirement 7 is dubious)
- `z` (doc says required, YAML/JSON schemas say optional)

Will update accordingy once we clarify.

cc @m-burgoyne @solson-nws @ShaneMill1 @chris-little

**Comment by chris-little** [comment]
@tomkralidis I think `coords` should be required for position, area, trajectory, etc, but optional or not required for `location` or `items`. 
I think `parameter-name` would optional if retrieving `items`, but otherwise required.
`z` could be optional for a "flat-earther" doing maps. We should make it easier for them too. Obviously error sconditions could exist if third dimension invoked.

@m-burgoyne @ShaneMill1 @iandruska-ibl But I could be wrong!

**Comment by m-burgoyne** [comment]
@tomkralidis This is an artifact of reusing YAML/JSON sub-schema files,  it can be resolved by making duplicates which for those queries where the shared parameters are optional and setting the appropriate attribute to reflect their status.

**Comment by chris-little** [comment]
EDR API SWG 43 agreed to close when PR merged
