### ISSUE TITLE
Suggestion: Add context / guidance / application material to README.md and Best Practice guide

### ISSUE THREAD

**Issue by bradh** [opengeospatial/ogcapi-environmental-data-retrieval#197]
Related to @chris-little comment at https://github.com/opengeospatial/joint-ogc-osgeo-asf-sprint-2021/issues/2#issuecomment-780012368, I think EDR would benefit from more context information about what it is (and is not).

I'm not part of the SWG, and am not sure if I care about this stuff or not.  The README.md vision starts with 

> The EDR API can be considered a 'Sampling API'. 

What am I sampling? Why? How?

The description uses terms like "data store resource" that probably makes sense if you already have a good understanding of the specific intended domain(s), but I can't tell what that is. I could maybe guess that "environmental data" might mean it can show me some kind of weather information, but I'm not sure if meant to be observations, warnings, forecasts. Is it meant to be used for other things? If so, what?

Apart from that, I'm still not sure where it fits into the other stuff that OGC is doing.

How does it relate to coverages or features?

How do I turn my query results into a visualisation (map, whatever) - is there some kind of style or process support that is meant to be used? 

If it is about weather and similar stuff, how do existing output format (things like WXXM/IWXXM, netCDF, GRIB) fit into this?

It might help if the README.md was less about the spec development process (e.g. historical sprints don't really tell me anything), and more about the output. Maybe some of the charter documentation could be refined and re-used as guidance material in the guidance document. Or maybe some blog posts.

**Comment by chris-little** [comment]
@bradh Good timing by you. Slow timing by us. We had a branch with a large revision to the Readme.md under review. I think it addresses all of your questions, but if not, here are some responses:
1. The 'Sampling' text was to satisfy OGC enthusiasts who have devoted a lot of time to sampling! You are sampling the data store by coordinate based queries.
2. The "data store resource" is just that - it may be environmental data, or it may be other data with engineering style coordinates. It could be a point cloud or a big gridded weather prediction, whether in a file store, one big file, a database, or cloud based containers.
3. The API is completely compatible with the OGC API-Features-Part 1: Core, but is agnostic about features or coverages. It is coordinate based.
4. You can turn the data into a visualisation with whatever tool you fancy, providing the API response payload format is supported. Leaflet and python tools all work fine.
5. If an EDR API service wishes to support IWXXM, NetCDF, GRIB, etc, response payload, it can. CoverageJSON was recommended, but not mandated, because it is flexible and not tied to a particular data model. If you wanted to retrieve a single value at a single point, you could return it in GRIB - not sensible but possible..
HTH

**Comment by chris-little** [comment]
@bradh I propose to close this issue tomorrow Thursday, 18 Feb 2021, after discussion in the regular meeting of the Standard WG.

**Comment by solson-nws** [comment]
Chris:

With the OGC/OSGeo/ASF sprint going through Friday, are we still having a
SWG mtg tomorrow?

Steve

**Comment by chris-little** [comment]
Steve,

Yes, I think so. It won’t take long, and we have some important issues to move along.

Chris
