### ISSUE TITLE
OGC candidate standard bypasses OGC data standards, relies on non-standard specification

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogcapi-environmental-data-retrieval#254]
For coverages, the document normatively references CoverageJSON which is not an OGC standard and known to be incompatible with the OGC coverage standards. The spec rather should normatively reference OGC Coverage Implementation Schema (CIS) 1.1, which additionally would yield (for free) a JSON and RDF encoding. ISO, OGC, and INSPIRE agree on this, and EDR thus is doomed to be incompatible with the mainstream of client and server implementations, as well as the services based on them.

**Comment by ghobona** [comment]
@pebau This issue has been [discussed](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues?q=is%3Aissue+is%3Aclosed+cis) several times.  The issue was [resolved](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/117#issuecomment-669735057) in a Cross-SWG setting between the EDR API SWG and Coverages SWG.

@chris-little I therefore propose that this new [Issue#254](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/254) is closed during the EDR API SWG meeting on 2021-03-18.

**Comment by pebau** [comment]
@ghobona I wouldn't see it as resolved technically, just administratively the issue is closed after group discussion. But the elephant remains in the room: CoverageJSON is not a standard, the WCS group simply has accepted a work item, but no harmonized version is on the horizon, and once done it [might be incompatible with current CoverageJSON](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/142#issuecomment-721931848). 
OTOH, the OGC Coverage JSON encoding exists and is proven; smaller fixes, if they occur (as with any standard), will be addressed by an active WG.
The spec under discussion completely bypasses the existing OGC standard. The result will be incompatibility by design, and definitely harmful.

**Comment by chris-little** [comment]
@pebau I agree with @ghobona: this has been discussed several times. You wrote:

> document normatively references CoverageJSON

This is NOT correct. The specification is not incompatible with CIS JSON. It is up to the service provider to decide what response formats to offer, as stated clearly in the specification and the GitHub repo, Coverage JSON was recommended, but not mandated, because:

1. There is usage and experience of CoverageJSON in various communities interested in the EDR API;
2. Several implementers have experience of CoverageJSON and prefer it as fit for purpose;
3. Several more implementers, not involved in the EDR API SWSG, are funding and planning to use EDR API  and will make their choices this year; 
4. CoverageJSON, like the EDR API, is relatively "data model agnostic" in that it is capable of supporting observational data and point clouds, as well as gridded data and other structures.
5. EDR API is a relatively generic API aimed at Web developers, not geospatial experts, and the 'market' and uptake will determine its success, not mandating specific solutions.

We will discuss the open issues on Thursday at 14:00 - 15:00 UTC (15:00 CET)

**Comment by chris-little** [comment]
EDR API SWG 47 agreed to close NOTUC
