### ISSUE TITLE
clarify inconsistency in coverages

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogcapi-environmental-data-retrieval#275]
(Preamble: as long as these issues get closed without decision documentation and, in particular, without a solution of the problem, I need to recreate them.)

EDR relies on CoverageJSON, a proprietary encoding of data elements; in its [current version](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/19-086.pdf) it does not mention the OGC coverage standard, CIS, at all. [A requirements class exists](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/candidate-standard/abstract_tests/covjson) only for CoverageJSON.

**Clearly EDR does not support OGC CIS and, by way of supporting CoverageJSON, explicitly is incompatible with OGC CIS.** ...contrary to the statements made in ticket comments.

Let us assume CIS is referenced alongside CoverageJSON as it was once. Then we have the issue that both are incompatible, as recognized since long, e.g., by the Coverages.SWG. A work item to make CoverageJSON compatible with CIS (so that it is justified to call it "Coverage"JSON) has been recognized, but there is no concerted activity aside from preliminary discussions. Hence, it cannot be expected that in the near future CoverageJSON will become compatible with CIS. In fact, doubts have been phrased that there is no sense in OGC offering two different JSON coverage encodings as this just fosters non-interoperability and confusion. Bottom line, the CoverageJSON data structure is different from and incompatible with OGC CIS. 

Hence, actions necessary include not "closing NOTUC without action" as previously but concretely:

- add requirements to connect to CIS JSON as a formally possible structure, at the [same level as CoverageJSON](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/candidate-standard/requirements)
- add concrete CIS JSON examples for at least the data structures mentioned in the document
- clarify in detail how the standard manages to support two incompatible JSON formats, and how users are expected to deal with this
 
PS: one comment said "CoverageJSON, like the EDR API, is relatively "data model agnostic" " - in fact, this just means there is no clear model behind, meaning data won't fit together in practice. No data model means no interoperability. (This is not an isolated opinion, but Computer Science and Information Technology 101.)

**Comment by KathiSchleidt** [comment]
Hi Peter,

don't think that's the current version - just checked, last updated 2 months ago, no idea where a more current version is hidden

According to rumors, the following will be added as an [appendix](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/candidate-standard/annex_relationship.adoc)

"data model agnostic" - from what I've understood, new-speak for "not modelled in UML" or "JSON Schema" - last I could discover the CovJSON YAML has some normatively informative status here

**Comment by pebau** [comment]
@KathiSchleidt hm, so the EDR group has submitted one document for approval and publishes another? I am puzzled. As I do not have time to wander through all sorts of documents I will wait for the authoritative version to appear.

PS: I like that: "normatively informative" !

**Comment by chris-little** [comment]
@pebau As stated several times, and in all versions of the spec, EDR API does not mandate any response format:
 
`Neither the [OGC API-Common] Core nor Collection requirements classes mandate specific encodings or formats for representing resources. The HTML, GeoJSON and CoverageJSON requirements classes specify representations for these resources in frequently used encodings for spatial data on the web.`

`None of these encodings are mandatory. An implementation of the EDR API may decide to implement another encoding instead of, or in addition to, those listed.`

If, as you say, CoverageJSON and CISJSON are incompatible, this EDR API repo is probably not the place to discuss and resolve that, as it is not an API issue. The statement `Clearly EDR does not support OGC CIS and, by way of supporting CoverageJSON, explicitly is incompatible with OGC CIS.` is misleading.

The various existing [implementations of EDR API](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/implementations.md) between them support CoverageJSON, NetCDF, GRIB and GeoSJON (I think the Wuhan University implementation uses GeoJSON to return data, but need to check). 

I think that there is a valid issue for this repo in your posting: does the [existing OpenAPIv3.0 definition of EDR API , using YAML](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/candidate-standard/openapi/schemas), prevent CIS JSON being used with the API?

If so, what should be changed?  The current implementers seem to be successfully returning a variety of response formats, including NetCDF and GRIB, which are supported by WCS and CIS, though these resources are not consumable by generic JSON orientated clients.

As the Planning Committee has now recommended the standard for approval to the Board of Directors, including changes to better align with other OGC APIs, such as Features and Records, and to improve the support of different response formats, I suggest that the SWG discuss this topic again, next week, if there are substantive technical changes to make, however minor. Otherwise, the issue should be closed so we can concentrate on the editorial work required for publication and the further development of the CITE Executable Test Suite. 

There are a number of proposed and funded implementations of EDR API in the pipeline. Perhaps some can be persuaded to develop CIS JSON support?

**Comment by KathiSchleidt** [comment]
@pebau Still not sure what the real version will be, but from the answers I've been getting the adoc fragments under https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/candidate-standard will eventually be merged. Only thing I can see clearly is that the full doc available from the root directory of this repository is 2 months old, thus cannot be current

@chris-little Is there a roadmap as of when a consolidated document will become available? I believe once we can take a look, we can then understand to what extent the CovJSON based JSON Schemas provided under https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/tree/master/candidate-standard/openapi/schemas will be normative, or informative, and understand which of the following hold true:

- If they are informative, I have no worries on replacing these schemas with the relevant bits required to describe and access CIS encoded coverages
- If they are normative (would seriously worry me, as they were clearly informative in the review version. I haven't been able to get a clear answer on this, what lead to my "normatively informative" quip from above), to my reading this tightly binds EDR to the CovJSON world, mostly useless beyond :(

**Comment by pebau** [comment]
@chris-little maybe we defer discussion until a stable document base is available?

**Comment by chris-little** [comment]
@pebau @KathiSchleidt The deadline from the OGC Staff for the final document is end of this month 2021-042-30.

**Comment by chris-little** [comment]
@pebau @KathiSchleidt the EDR API document is technically frozen, and minor editorial changes are being accumulated in a recent branch from the Master version. The deadline for these editorial changes is 2021-04-28 - next Wed.

As stated before, the CoverageJSON conformance, and hence the yaml schema describing a CoverageJSON response is optional.

I recommend that you read the [repo version](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/CopyMaster20210420/candidate-standard/EDR-candidate-specification.adoc), as we still have not figured out why the nightly automatic build stopped working. 

Cana we close this issue?
