### ISSUE TITLE
Negative interval in extent?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-environmental-data-retrieval#388]
On this line:

https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/collections/extent.yaml#L221

A -50 interval is uses, however the second part of repetitions is supposed to be a minimum value.
Is that a mistake?

@m-burgoyne @chris-little

**Comment by chris-little** [comment]
@jerstlouis There is a mistake, but it is not the `-50`, which enables the vertical coordinate to be decremented from 1000 to 950 to 900 to 850  ... etc.
The mistake is the `R50` - do the decrement 50 times, which means the vertical coordinate (e.g. pressure) would become negative. The repetition factor should be no more than R20, so that the values decrement to exactly zero.
The next PR from @m-burgoyne will correct the example.

**Comment by dblodgett-usgs** [comment]
Fixed in #390
